# Generated by Django 3.2.16 on 2022-10-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chiamate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_creation', models.DateTimeField(auto_now_add=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('chiamata', models.TextField(blank=True)),
                ('status', models.CharField(max_length=255)),
                ('server', models.CharField(max_length=255)),
                ('risposta_server_terzo', models.TextField(blank=True)),
            ],
        ),
    ]
